// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'VehicleData.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

VehicleData _$VehicleDataFromJson(Map<String, dynamic> json) {
  return VehicleData(
    json['vehicleId'] as String?,
    json['ouid'] as String?,
    (json['lat'] as num?)?.toDouble(),
    (json['lng'] as num?)?.toDouble(),
    json['ignition'] as bool?,
    json['speed'] as int?,
    json['alias'] as String?,
    json['ac'] as bool?,
    json['driverName'] as String?,
    json['driverPhoneNo'] as String?,
    json['direction'] as int?,
    json['vehicleNo'] as String?,
    json['iemi'] as String?,
    json['address'] as String?,
    json['lastUpdated'] as String?,
    json['state'] as String?,
    json['elapsedTime'] as String?,
    json['simNo'] as String?,
    json['deviceType'] as String?,
    json['terminalPacketMeta'] == null
        ? null
        : TerminalPacketMeta.fromJson(
            json['terminalPacketMeta'] as Map<String, dynamic>),
    json['since'] as String?,
    json['devicePassword'] as String?,
    json['company'] as String?,
    json['transporterUsername'] as String?,
    json['vehicleType'] as String?,
    json['todayKm'] as int?,
    json['todayDu'] as String?,
    json['poi'] as String?,
    json['lock'] as bool?,
    (json['odometer'] as num?)?.toDouble(),
    json['distanceFromLastStop'] as String?,
    json['durationFromLastStop'] as String?,
    json['stoppageHaltTime'] as String?,
    json['lockEnable'] as bool?,
    json['acCompatible'] as bool?,
    json['lockFromApi'] as bool?,
    json['active'] as bool?,
    (json['mileage'] as num?)?.toDouble(),
    json['remark'] as String?,
    json['extraRemark'] as String?,
    json['loadingStatus'] as String?,
    json['overspeed'] as int?,
    json['analog'] as bool?,
    (json['fuelRemain'] as num?)?.toDouble(),
    (json['todayFuelConsumed'] as num?)?.toDouble(),
  );
}

Map<String, dynamic> _$VehicleDataToJson(VehicleData instance) =>
    <String, dynamic>{
      'vehicleId': instance.vehicleId,
      'ouid': instance.ouid,
      'lat': instance.lat,
      'lng': instance.lng,
      'ignition': instance.ignition,
      'speed': instance.speed,
      'alias': instance.alias,
      'ac': instance.ac,
      'driverName': instance.driverName,
      'driverPhoneNo': instance.driverPhoneNo,
      'direction': instance.direction,
      'vehicleNo': instance.vehicleNo,
      'iemi': instance.iemi,
      'address': instance.address,
      'lastUpdated': instance.lastUpdated,
      'state': instance.state,
      'elapsedTime': instance.elapsedTime,
      'simNo': instance.simNo,
      'deviceType': instance.deviceType,
      'terminalPacketMeta': instance.terminalPacketMeta,
      'since': instance.since,
      'devicePassword': instance.devicePassword,
      'company': instance.company,
      'transporterUsername': instance.transporterUsername,
      'vehicleType': instance.vehicleType,
      'todayKm': instance.todayKm,
      'todayDu': instance.todayDu,
      'poi': instance.poi,
      'lock': instance.lock,
      'odometer': instance.odometer,
      'distanceFromLastStop': instance.distanceFromLastStop,
      'durationFromLastStop': instance.durationFromLastStop,
      'stoppageHaltTime': instance.stoppageHaltTime,
      'lockEnable': instance.lockEnable,
      'acCompatible': instance.acCompatible,
      'lockFromApi': instance.lockFromApi,
      'active': instance.active,
      'mileage': instance.mileage,
      'remark': instance.remark,
      'extraRemark': instance.extraRemark,
      'loadingStatus': instance.loadingStatus,
      'overspeed': instance.overspeed,
      'analog': instance.analog,
      'fuelRemain': instance.fuelRemain,
      'todayFuelConsumed': instance.todayFuelConsumed,
    };
